### ISSUE TITLE
cargo-chef is not listed in `awesome-rust`

### ISSUE THREAD

**Issue by prestontw** [LukeMathWalker/cargo-chef#121]
I was scrolling through `awesome-rust` looking for some educational materials, and, to my surprise, `cargo-chef` is not listed under the Deployment > Docker section: https://github.com/rust-unofficial/awesome-rust#deployment

Would we be interested in adding this tool to that list of awesome tools?

**Comment by LukeMathWalker** [comment]
If you want to open a PR for it, I have nothing against it 😄

**Comment by prestontw** [comment]
Link to PR: https://github.com/rust-unofficial/awesome-rust/pull/1248

**Comment by prestontw** [comment]
PR is merged in! It's visible now: https://github.com/rust-unofficial/awesome-rust#deployment
