### ISSUE TITLE
Feature request: automatically edit `Cargo.toml` for large workspaces

### ISSUE THREAD

**Issue by prestontw** [LukeMathWalker/cargo-chef#125]
Hello! My workspace at work is _massive_. We build Docker images for individual components from this monorepo. Rather than copying over the entire monorepo for each individual component, we copy over our main monolithic backend directory or smaller individual services directories.

All of these `Dockerfile`s have 
```
RUN perl -0777 -i -pe 's/members = \[[^\]]+\]/members = ["individual-component"]/igs' Cargo.toml
```
because `cargo` will still compile other components even when specifying `--package` or `--bin`. 

I would like to request an enhancement: that cargo chef would handle this automatically. I have built a small repo that replicates this behavior: https://github.com/prestontw/cargo-chef-workspace-experiment. 

I could imagine that specifying `--bin`, `--package`, or something else (maybe `--only`?) would edit the `Cargo.toml` file in the event where the entire folder structure isn't copied over.

**Comment by prestontw** [comment]
Looking at the code (and since this happens in the same stage as `prepare`), I would guess that this would be a flag to `Prepare` rather than `Cook`. (Wow! It seems like most flag work is for `Cook`. Interesting change of pace!)

**Comment by prestontw** [comment]
Thinking about it some more, I think a `--member` argument might work nicely. It's distinct from `--package` to avoid conflating usage and more clearly (hopefully) conveys that it would edit the `members` field. I might take a quick stab at implementing this.

**Comment by LukeMathWalker** [comment]
> because cargo will still compile other components even when specifying --package or --bin.

I am not sure this is true. I cloned your repository and ran `cargo b --bin backend`: `cargo` only built the `backend` crate. You can double-check this as well using the `--timings` flag:

![image](https://user-images.githubusercontent.com/20745048/163780534-0880c93d-d842-4add-9439-54a214910ccd.png)

**Comment by prestontw** [comment]
> > because cargo will still compile other components even when specifying --package or --bin.
> 
> I am not sure this is true. I cloned your repository and ran `cargo b --bin backend`: `cargo` only built the `backend` crate. 

Ahh, nice. I should have been more precise. `cargo` will not compile `ci`, but it will check that its folder, workspace, and Cargo.toml structure is correct.

Replicating what you did (on commit `e0196d317e20cf1a8e80784d484f4903b40e5799` in the repro repo):
```
preston@Prestons-MBP cargo-chef-workspace-experiment % cargo b --bin backend
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
preston@Prestons-MBP cargo-chef-workspace-experiment % rm ci/Cargo.toml 
preston@Prestons-MBP cargo-chef-workspace-experiment % cargo b --bin backend
error: failed to load manifest for workspace member `/Users/preston/git/cargo-chef-workspace-experiment/ci`

Caused by:
  failed to read `/Users/preston/git/cargo-chef-workspace-experiment/ci/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```
Building works fine, but if `cargo` can't find the `Cargo.toml` file for a member, it won't even get to the build step. 

Does that clear things up? The case where we don't have `ci/Cargo.toml` represents the directory structure for my work Dockerfiles.

**Comment by LukeMathWalker** [comment]
I see, thanks for clarifying!

I am not inclined to merge the PR as is. If we want to support this usecase, I suggest a different strategy, which I believe is more general and could be useful for a broader class of usecases:

- Add a `--bin` flag to `cargo chef prepare`. `cargo chef prepare` would then prepare the _minimal_ skeleton required to compile that binary, removing all crates from the workspace that do not appear in the dependency tree of the specified binary.
- Add a `--bin` flag to `cargo chef cook`.

**Comment by prestontw** [comment]
> If we want to support this usecase, I suggest a different strategy, which I believe is more general and could be useful for a broader class of usecases

Ooh, I'm always down for adding more general functionality. What scenarios are you thinking that this would be useful than the minimal approach I've implemented?

I think editing the `members` array is necessary anyway for that more general functionality. If we only remove the unused crates and keep the root-level `Cargo.toml` as it is, we will run into the same error message as above. What do you think about changing the `--member` flag in the PR to `--bin` and then preparing the minimal skeleton as an optimization later? The interface wouldn't change, but people would pick up a nice optimization! This could also solve the immediate problem and provide data on whether the more general functionality is something that people look to cargo-chef for or something that they do manually in their Dockerfile.

**Comment by LukeMathWalker** [comment]
In terms of philosophy, `cargo-chef` follows two principles:

- Stick close to `cargo`'s API (whenever possible). People already know `cargo`, making it easier to pick up `cargo-chef` by mimicry;
- Be declarative ("Tell me what you want to accomplish, I'll figure out how").

`--members` satisfies neither: it's a divergence from `cargo`'s API and it's imperative. The user needs to track down, manually, which members of the workspace are required to successfully build the binary.
 
`--bin`, instead, ticks both boxes: it mirrors an existing `cargo` option and it's declarative ("I want to compile this binary and get as many cache hits as possible, you figure out how").

But we cannot take you PR for `--members`, rename the option to `--bin` and call it a day: if we replace the `members` field with just the target binary, compilation is going to fail for workspaces where the binary depends on other local libraries. That would be extremely surprising for the user.  
If we want to slice this feature down in incremental iteration, I suggest the following:

- Add a `--bin` option to `cook`;
- Add a `--bin` option to `prepare` that only removes other binaries from the `members` fields, keeping all libraries there;
- Improve on the above by keeping as members only the local libraries that are required to build the specified binary.

At any stage of the above, we have something functional that behaves as expected.

**Comment by prestontw** [comment]
> In terms of philosophy, `cargo-chef` follows two principles:
> 
> * Stick close to `cargo`'s API (whenever possible). People already know `cargo`, making it easier to pick up `cargo-chef` by mimicry;
> * Be declarative ("Tell me what you want to accomplish, I'll figure out how");
> * Fail predictably and loudly.

These make sense to me for philosophy. I will respond to the rest of your post below. I do not mean to be caustic, but I have a use case in mind and your post does not seem to address it. I am hoping to align on the use case that I have in mind first before talking about implementation approaches and tradeoffs.

At work, we have a very large directory, consisting of backend (rust), front end (js/ts), and deployment and ci projects (rust). These are all separate directories, but all of the rust projects are members of the same root workspace. All together, there are ~280 workspace members (libraries and binaries), but only 20 services. Cargo, when building, will check to make sure that all members of the workspace are valid and it can read their Cargo.toml files. To avoid copying, say, deployments utility projects when producing an image for a backend service, we edit the Cargo.toml using a perl script to only include the backend service. The alternative would be to maintain the entire folder structure for all members in the workspace (see https://github.com/rust-lang/cargo/issues/2644#issuecomment-474155460). Rather than needlessly copying information around, we edit the Cargo.toml instead. This feature request is to fold that editing functionality into `cargo-chef`.

> `--members` does not satisfy 1. and 2.: it's a divergence from `cargo`'s API and it's imperative. The user needs to track down, manually, which members of the workspace are required to successfully build the binary.

At work, I have 20 Dockerfiles that contain some perl script to edit Cargo.toml's `members` field to only the binary that we want to build. There are certain cases where it includes more than just the binary---say, a templating library that we have as a utility to render configs before baking them into the image---but those are not libraries, they are utility binaries that we use in the making of the final image. In terms of
> The user needs to track down, manually, which members of the workspace are required

this is untrue. The only thing that is required is the member that we wish to build. Effectively, specifying `--member` (or `--bin` if that works as a better name) is in terms of the final binary that we wish to produce, similar to `cargo build --bin`. We don't need to specify members that are dependencies of this member---each Dockerfile I have at work is a testament to this---they don't include their dependency members in their perl script. I can add this to the minimal repo if that would be useful, but intuitively it's as if someone has a local dependency that they downloaded that is not part of the workspace. It's similar to having a local fork of `diesel-rs` locally that I'm using for some backend application that I specify as a dependency vai `path`---it's not part of my workspace, but Cargo still knows how to fold it in as a dependency since I specify it as a dependency via `path`.

All that to say that this is approach does not strike me as imperative, any more than specifying `--bin` would be: both are in terms of the final binary that we want to build.

I agree that it is a divergence from `cargo`'s API, but I didn't want consumers to be confused between the two. "If I'm building a binary, do I need to specify `--bin` when either `cook`ing or `prepare`ing?" Not necessarily, only if you have a particular directory and workspace structure. I guess there's no harm in it if you have a simple non-workspace Cargo.toml, but it still isn't the exact right mental model of behavior. That's why I was leaning towards using something other than `--bin`, but I'm happy to do whatever makes sense.

> `--bin`, instead, ticks both boxes: it mirrors an existing `cargo` option and it's declarative ("I want to compile this binary and get as many cache hits as possible, you figure out how").

I'm noting that `--bin` would still need to edit the `members` field of the root `Cargo.toml`, otherwise we will get the error above. In actually, we would get "more" of them because we would have removed even more unused workspace members.

I do like that `--bin` would give the possibility of achieving more cache hits, but I think that it would be unlikely since someone would more likely be editing workspace member dependencies when developing rather than unneeded dependencies. In that case, the cache would still get invalidated.

> But we cannot take you PR for `--members`, rename the option to `--bin` and call it a day: if we replace the `members` field with just the target binary, compilation is going to fail for workspaces where the binary depends on other local libraries.

This is not true. I can add an example to the above reproducing repo if that would be helpful (I might do it anyway since it should be quick to do).

> If we want to slice this feature down in incremental iteration, I suggest the following:
> 
> * Add a `--bin` option to `cook`;
> * Add a `--bin` option to `prepare` that only removes other binaries from the `members` fields, keeping all libraries there;

The important bit here to remove from the `members` fields is projects outside of what we have copied over. That might actually be a more fine-grained next step than specifying which `member` we want. The important thing isn't that we remove all but the binary member, the important thing is that we only have members that we have access to in docker.

---------------------

Hopefully that makes sense! Please let me know if the feature (reducing the number of docker steps and removing a dependency on perl) makes sense with this context. I will add a library dependency to the minimal repo to show that it still works. After all that, please let me know if the already implemented approach is satisfactory or if you would prefer the more general version where we remove members that are not copied over to docker. I would prefer to merge the version that is already implemented so I can start benefitting from it now then implement removing only members that are not copied over to docker as a refinement.

**Comment by prestontw** [comment]
> I will add a library dependency to the minimal repo to show that it still works

I've added a `util` folder in https://github.com/prestontw/cargo-chef-workspace-experiment/commit/f5a40f1c698153c3329c572f1f32f37fafff50e0 and copied over `util` to the docker image in https://github.com/prestontw/cargo-chef-workspace-experiment/commit/4d32d4355a59c491f3c82a61235c3574b768d74c. Now it works! Note that the `members` field is the same, but we are still able to build. Hopefully this addresses that `--members` isn't deterministic: I did not have to specify all of the dependencies in the `members` field.

But, I also think that the more automatic version that removes members based on whether those files are copied over is maybe better. What do you think? Even if that's the approach that we go with, is the problem space (or lack of problems with the `--members` approach) a little clearer now?

**Comment by prestontw** [comment]
> But, I also think that the more automatic version that removes members based on whether those files are copied over is maybe better

Maybe I'm jumping the gun, but I implemented this in https://github.com/LukeMathWalker/cargo-chef/pull/127. It passes the test that I originally wrote for the other implementation, but there are still some kinks that I need to work out for the minimal repo: I'm still getting the `failed to read Cargo.toml` error. This is probably because I'm not editing the `Cargo.toml` before I parse all of them.

**Comment by LukeMathWalker** [comment]
> this is untrue. The only thing that is required is the member that we wish to build. Effectively, specifying --member (or --bin if that works as a better name) is in terms of the final binary that we wish to produce, similar to cargo build --bin. We don't need to specify members that are dependencies of this member---each Dockerfile I have at work is a testament to this---they don't include their dependency members in their perl script. I can add this to the minimal repo if that would be useful, but intuitively it's as if someone has a local dependency that they downloaded that is not part of the workspace. It's similar to having a local fork of diesel-rs locally that I'm using for some backend application that I specify as a dependency vai path---it's not part of my workspace, but Cargo still knows how to fold it in as a dependency since I specify it as a dependency via path.

You are right. I tried it out and that's indeed the case - the crate builds because it sees the other local members as "simple" path dependencies.  
There are a few other options that can be specified in the workspace root. Quoting `cargo`'s manifest format docs:

> The [[patch]](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section), [[replace]](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-replace-section) and [[profile.*]](https://doc.rust-lang.org/cargo/reference/profiles.html) sections in Cargo.toml are only recognized in the root manifest, and ignored in member crates' manifests.

It does not look like they would lead to breakage if libraries are removed from the members list, so we should be good there.

> I agree that it is a divergence from cargo's API, but I didn't want consumers to be confused between the two. "If I'm building a binary, do I need to specify --bin when either cooking or prepareing?" Not necessarily, only if you have a particular directory and workspace structure. I guess there's no harm in it if you have a simple non-workspace Cargo.toml, but it still isn't the exact right mental model of behavior. That's why I was leaning towards using something other than --bin, but I'm happy to do whatever makes sense.

The same "confusion" arises in `cargo` itself. Rust developers have learned, by using `cargo`, that specifying `--bin` is optional if they have a single bin but beneficial when they have multiple and they are only interested in compiling a specific one.
I don't see this as an issue, on the contrary: the situations where you would go as far as specifying `--bin` for `cargo`'s commands are exactly the same where you would benefit from specifying `--bin` in `cargo-chef`'s commands.

> I do like that --bin would give the possibility of achieving more cache hits, but I think that it would be unlikely since someone would more likely be editing workspace member dependencies when developing rather than unneeded dependencies. In that case, the cache would still get invalidated.

This is not necessarily the case. If you have a sizeable company-wide monorepo, there is a high likelihood that other teams have touched a library that sits in the same workspace but isn't actually used by your binary.

> But, I also think that the more automatic version that removes members based on whether those files are copied over is maybe better. What do you think? Even if that's the approach that we go with, is the problem space (or lack of problems with the --members approach) a little clearer now?

Just to clarify - I understand the problem space, but I am not willing to address the problem when framed as a monorepo management problem. This is not the focus of `cargo-chef` and it's not complexity I am willing to take on.  
In order to help you, I am instead trying to frame your monorepo management problem as a cache hit optimization problem (`cargo-chef`'s reason to exist) which _also_ happens to solve your specific issue.

**Comment by prestontw** [comment]
> The same "confusion" arises in `cargo` itself. Rust developers have learned, by using `cargo`, that specifying `--bin` is optional if they have a single bin but beneficial when they have multiple and they are only interested in compiling a specific one.
> I don't see this as an issue, on the contrary: the situations where you would go as far as specifying `--bin` for `cargo`'s commands are exactly the same where you would benefit from specifying `--bin` in `cargo-chef`'s commands.

Ahh, yes, that makes sense. 

> This is not necessarily the case. If you have a sizeable company-wide monorepo, there is a high likelihood that other teams have touched a library that sits in the same workspace but isn't actually used by your binary.

This makes sense too. I am wondering: do you think that this would address one of cargo-chef's limitations (from the README) that 
> `cargo build` will build local dependencies (outside of the current project) from scratch

I'm wondering even if we make the minimal skeleton if a lot of these local dependencies would be rebuilt anyway, especially for large monorepos.

> I am not willing to address the problem when framed as a monorepo management problem. This is not the focus of `cargo-chef` and it's not complexity I am willing to take on.
> In order to help you, I am instead trying to frame your monorepo management problem as a cache hit optimization problem (`cargo-chef`'s reason to exist) which _also_ happens to solve your specific issue.

(We are now talking about the automatic approach, correct?) I see your distinction, but similar to 
> generate fewer intermediate Docker layers (for workspaces)

from [the README](https://github.com/LukeMathWalker/cargo-chef#limitations-and-caveats) and 
> I think that tools like `cargo-chef`, if they want to be adopted and trusted, should strive to keep the simplest interface with the minimal possible number of downsides.

from [an earlier conversation we had on a different PR](https://github.com/LukeMathWalker/cargo-chef/pull/70#issuecomment-894107655), the automatic approach seems to me to match the current benefits of `cargo-chef` (fewer intermediate layers) and requires no interface changes, which seems the simplest to me. The main downside seems to be complexity? [My implementation of this](https://github.com/LukeMathWalker/cargo-chef/pull/127) doesn't seem too complex, but I'm interested in what you think. 

I think generally, we need something to make `cargo-chef` pleasant to work with in workspaces: having to match the filesystem outside of docker inside the build docker stage is surprising, and it would be awesome if `cargo-chef` could handle this for people and workspaces (opening up `cargo-chef` to be used in more projects). I'm now leaning towards doing automatic removal of workspace members based on whether we can find their Cargo.toml files or not, but if we end up going with something like https://github.com/LukeMathWalker/cargo-chef/pull/126 I think that would solve my problem.

What do you think? I'm waiting to hear back from you on whether the automatic approach in https://github.com/LukeMathWalker/cargo-chef/pull/127 is complex before making changes in https://github.com/LukeMathWalker/cargo-chef/pull/126 since I prefer https://github.com/LukeMathWalker/cargo-chef/pull/127 now. (I kind of feel like we have swapped implementation ideas! 127 is somewhat similar to what you were suggesting with removing the binary members automatically, but it addresses the issue more directly.)

**Comment by LukeMathWalker** [comment]
I don't like #127 - we are assuming that missing `Cargo.toml`s for workspace members are an intentional choice, while they could very well be a mistake that should lead to a failure instead of us trying to "make it work".
We should only be removing members from the workspace members list when doing so helps us in fulfilling the user's stated intent (i.e. why I want `--bin` for this).

**Comment by prestontw** [comment]
> while they could very well be a mistake that should lead to a failure instead of us trying to "make it work".

I'm trying to think of a scenario in which this would't lead to a failure if it is a mistake. If it's not copied over and not copying over is a mistake, then it's probably because it's a dependency, right? At which point they would get a compile error when they try to use a dependency that doesn't exist. Or is there some other scenario in which this would come up?

**Comment by LukeMathWalker** [comment]
Simplest case (happens to me regularly) - you delete the files for a binary or a library from the workspace but forget to remove them from the `members` list.

**Comment by prestontw** [comment]
> Simplest case (happens to me regularly) - you delete the files for a binary or a library from the workspace but forget to remove them from the `members` list.

Hmm, interesting. Running `cargo test` or `cargo build` outside of `cargo-chef` would reveal the problem, right? I understand that `cargo-chef` is removing something broken for people automatically, but other tools would reveal that something is broken. `--bin` would also paper over this since we would just blast away all other members.

**Comment by LukeMathWalker** [comment]
> Hmm, interesting. Running cargo test or cargo build outside of cargo-chef would reveal the problem, right? I understand that cargo-chef is removing something broken for people automatically, but other tools would reveal that something is broken. --bin would also paper over this since we would just blast away all other members.

We should make no assumptions on the other guard rails that people might have on their own projects.  
`--bin` would paper over the issue, but it doesn't matter because intent is clear there: get this binary compiled for me, building the minimum number of dependencies and maximising my cache hit ratio. They clearly don't want to build the entire workspace, therefore we don't care if something else might be broken. We can't make the same assumption if we are just asked to build the current workspace with no further specifications.

I'm quite convinced at this point that the `--bin` approach is the optimal one for the goals of this library. If we want to get this in, let's move forward with that.

**Comment by prestontw** [comment]
> Going to back to the implementation details, based on the new information I suggest:
> 
> * Add a --bin option to cook;
> * Add a --bin option to prepare that edits the `members` list to include just the specified binary.
> 
> This is fairly close to the work you did in #126, we are just missing the `cook` part and an option renaming.

I implemented this in https://github.com/LukeMathWalker/cargo-chef/pull/126/commits/9ef2aeabb8e24fd67741f7dfc59587eb634d70fd. What do you think about including the `--bin` argument in the serialized skeleton? Then we can check if they are the same across prepare and cook. (If you would also prefer to move implementation details discussion to the PR, that makes sense to me!)

**Comment by LukeMathWalker** [comment]
This has been implemented in #126 🚀

**Comment by prestontw** [comment]
I'm excited to tell some of my old coworkers about this! I think they might still run into other issues that I've reported here, but hopefully it makes the [project directory structure issue](https://github.com/rust-lang/cargo/issues/2644#issuecomment-474155460) we link to in each Dockerfile more discoverable.

**Comment by prestontw** [comment]
> I'm excited to tell some of my old coworkers about this! 

Speaking of sharing, do you mind if I write up a little reddit post about this, mentioning that this feature is in the new release?

**Comment by LukeMathWalker** [comment]
> > I'm excited to tell some of my old coworkers about this!
> 
> Speaking of sharing, do you mind if I write up a little reddit post about this, mentioning that this feature is in the new release?

Not at all, go ahead 😁

**Comment by prestontw** [comment]
Took me a bit, and looks like there's been several releases since then, but here it is! https://www.reddit.com/r/rust/comments/wvf7a3/cargochef_released_with_docker_workspace_member/
