### ISSUE TITLE
Cargo chef bug with cargo.toml [[bin]] targets

### ISSUE THREAD

**Issue by Voxelot** [LukeMathWalker/cargo-chef#128]
Repro: 
```
git clone https://github.com/FuelLabs/sway
cd sway
git checkout cargo-chef
docker build -f deployment/Dockerfile .
```
error:
```
Caused by:
  failed to parse manifest at `/build/sway-ir/Cargo.toml`

Caused by:
  can't find `opt` bin at `src/bin/opt.rs` or `src/bin/opt/main.rs`. Please specify bin.path if you want to use a non-default path.
```

This error doesn't make sense, as `opt.rs` *does* exist at [`sway-ir/src/bin/opt.rs`](https://github.com/FuelLabs/sway/blob/v0.11.0/sway-ir/src/bin/opt.rs). When I remove the target definition from the [Cargo.toml](https://github.com/FuelLabs/sway/blob/v0.11.0/sway-ir/Cargo.toml#L11) file, it works. While having the target defined there is unnessecary, it shouldn't break cargo-chef.

**Comment by LukeMathWalker** [comment]
This should have been fixed in the latest release thanks to #133!

**Comment by LukeMathWalker** [comment]
Do you have multiple binaries in that package?

**Comment by Dessix** [comment]
That crate has only one, with just the explicit bin name.

The workspace has dozens of crates, but the one that had issues is two directories deep- I’m not sure if that had any significance and won’t have time to repro further until Monday, if needed.
