### ISSUE TITLE
error: failed to download `aho-corasick v0.7.18`

### ISSUE THREAD

**Issue by ash-hashtag** [LukeMathWalker/cargo-chef#139]
------
 
While building docker image,
at
> [cacher 4/4] RUN cargo chef cook --release --recipe-path recipe.json:
#13 0.774     Updating crates.io index
#13 1.664  Downloading crates ...
#13 1.689 error: failed to download `aho-corasick v0.7.18`
#13 1.689
#13 1.689 Caused by:
#13 1.689   unable to get packages from source
#13 1.689
de: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.37/src/recipe.rs:156:27
#13 1.693 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------
executor failed running [/bin/sh -c cargo chef cook --release --recipe-path recipe.json]: exit code: 101

14 3.488 note: this is an unexpected cargo internal error
#14 3.488 note: we would appreciate a bug report: https://github.com/rust-lang/cargo/issues/
#14 3.488 note: cargo 1.62.0 (a748cf5a3 2022-06-08)
#14 3.492 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.37/src/recipe.rs:156:27
#14 3.492 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by LukeMathWalker** [comment]
This is an issue with `cargo` and crates.io.

**Comment by ash-hashtag** [comment]
when I opened this issue there, they told it's cargo-chef issue :( and redirected me here

**Comment by LukeMathWalker** [comment]
`cargo-chef` simply invokes `cargo build`, no magic at play.
