### ISSUE TITLE
Caching doesn't work when `strip = "debuginfo"` is set

### ISSUE THREAD

**Issue by jcaesar** [LukeMathWalker/cargo-chef#149]
Quick reproducer

```bash
cargo new foo
cd foo
cargo add rand # Example dependency

echo '                           
[profile.release]
strip = "debuginfo"' >>Cargo.toml

echo 'FROM clux/muslrust:1.63.0 AS chef
RUN cargo install cargo-chef --locked
WORKDIR /usr/src/foo

FROM chef AS planner
COPY . .
RUN cargo chef prepare

FROM chef AS builder
COPY --from=planner /usr/src/foo/recipe.json recipe.json
RUN cargo chef cook --release
COPY . .
RUN cargo build --release
' | docker build -f- .
```
(See that rand is built twice in the output)

**Comment by Sculas** [comment]
I'm experiencing this issue as well.

**Comment by fmckeogh** [comment]
Same here

**Comment by philippeitis** [comment]
It seems that this occurs when using `strip = true` as well (which strips symbols).

My (temporary) solution was removing `strip = true` from `Cargo.toml` and adding `RUN strip /path/to/binary` to my `Dockerfile` after the build stage.

**Comment by divergentdave** [comment]
I have run into this issue as well with `strip = true`. I looked at the canonicalized `Cargo.toml` file inside the recipe file, and compared to the profile definitions in the original `Cargo.toml`, it is missing the strip attribute.

**Comment by LukeMathWalker** [comment]
Fixed in `cargo-manifest` and picked by `cargo-chef` in 17a9e0d, it's going out with 1.60.0. Thanks for your help @divergentdave!
