### ISSUE TITLE
Should I set CARGO_INCREMENTAL=0?

### ISSUE THREAD

**Issue by KonradHoeffner** [LukeMathWalker/cargo-chef#151]
I assume that building a Docker image does not profit from incremental compilation, is that correct?
If yes, should I run `RUN CARGO_INCREMENTAL=0 cargo build` in the Dockerfile?
However the examples don't use that, is there a reason for that?

**Comment by LukeMathWalker** [comment]
That sounds correct.
If your dependencies are absolutely unchanged, you'll get a layer cache hit.
If your dependencies have changed, you'll get a cache miss and complete rebuild.

We should update the README to include it as an optimization!

**Comment by KonradHoeffner** [comment]
Sorry, I didn't fully understand this. Isn't it good to get a cache hit? Do I get the cache hit with or without disabling incremental builds?
Is `CARGO_INCREMENTAL=0` the optimization or `CARGO_INCREMENTAL=1` (the default).

**Comment by LukeMathWalker** [comment]
CARGO_INCREMENTAL has no influence on you getting a cache hit or a cache miss.
What it does, though, is generate extra artifacts that make you caching layers bigger (therefore slower to upload/download). By setting it to 0, your builds should get faster (in all cases, both hits and misses).

**Comment by KonradHoeffner** [comment]
Thank you for the clarification, now I understand it completely!
