### ISSUE TITLE
Failing to get a dependency that's hosted on our private repository.Is there any workaround to neglect those dependencies.

### ISSUE THREAD

**Issue by Mohan6677** [LukeMathWalker/cargo-chef#155]
Caused by:
  [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: self signed certificate in certificate chain); class=Net (12)
thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.45/src/recipe.rs:166:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by LukeMathWalker** [comment]
This has nothing to do with `cargo-chef` - if `cargo` can fetch it, so can `cargo-chef`. This looks like an issue around authorization that you need to solve when building a Docker image.

**Comment by Mohan6677** [comment]
that is because we have set CARGO_NET_GIT_FETCH_WITH_CLI , GIT_SSL_NO_VERIFY to TRUE  AND git config http.sslVerify to false.

**Comment by sirodoht** [comment]
@LukeMathWalker Hey, I'm facing the same issue but I can verifiably get it to work with just cargo using `ENV CARGO_NET_GIT_FETCH_WITH_CLI=true` but it doesn't look like cargo-chef is picking up the variable. Is that possible?
