### ISSUE TITLE
Missing docker image(s)

### ISSUE THREAD

**Issue by miraclx** [LukeMathWalker/cargo-chef#175]
Hey man, just saw you just made an update. Although, it looks like the [`latest-rust-1.65.0`](https://hub.docker.com/r/lukemathwalker/cargo-chef/tags?name=latest-rust-1.65.0) docker image no longer exists.

Filing this issue because I don't think that was intentional.

**Comment by miraclx** [comment]
Ah, looks like a [push failed](https://github.com/LukeMathWalker/cargo-chef/actions/runs/3664215931) for a reason that's already been [fixed on master](https://github.com/LukeMathWalker/cargo-chef/compare/d864733f45f5e6e5dff6e9fd4282bed606af9fb9...ba8604ff1a0bade913737a0fe4b1e46fecfd4b52).

Although, inferring from [the last run attempt](https://github.com/LukeMathWalker/cargo-chef/actions/runs/3670524378), it looks like we have a race condition. Some workflow runs executed before the crate was published on crates.io.

Looks like this should be fixed by attempting a retry, 🤷🏽‍♂️

**Comment by LukeMathWalker** [comment]
All Docker images should be fixed now that the daily cronjob has run 👌🏻 

I apologies for the temporary issue due to my deletion of `0.49.0` artifacts.
