### ISSUE TITLE
Cargo chef cook fails on custom build targets

### ISSUE THREAD

**Issue by Qqwy** [LukeMathWalker/cargo-chef#177]
Given a custom target specified using a local JSON file, such as [this one](https://github.com/rust-wii/ogc-rs/blob/master/powerpc-unknown-eabi.json), when running e.g.

```
cargo +nightly chef cook --no-std --recipe-path recipe.json -Z build-std=core,alloc --target powerpc-unknown-eabi.json
```

Results in the following crash:

```
   Compiling some-dependency-name v0.0.1 (/app/lib)
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
Error: Failed to cook recipe.

Caused by:
    0: Failed to clean up dummy compilation artifacts.
    1: IO error for operation on /build/target/powerpc-unknown-eabi.json/debug: No such file or directory (os error 2)
    2: No such file or directory (os error 2)
```

It seems like in https://github.com/LukeMathWalker/cargo-chef/blob/37834d588b0f0dc792fc2f755060add906c4ffa9/src/skeleton/mod.rs#L241 the value of the `--target` argument is 1:1 used as folder name.

It is not strange that this feature is missing, as I believe it is a nightly feature. 
Nonetheless, its usage seems prevalent in embedded Rust: https://docs.rust-embedded.org/embedonomicon/custom-target.html .

As such, it would be nice if it could be supported. I'd happily contribute a PR for this.

**Comment by LukeMathWalker** [comment]
TIL!
A PR would be welcome.
