### ISSUE TITLE
Strange issue: Small binary that immediately crashes

### ISSUE THREAD

**Issue by gitmalong** [LukeMathWalker/cargo-chef#186]
Hi!

Will post a Docker another day because I don't have it available right now. I'm facing the issue that the produced binary is just around 1.5MB instead of around 7MB and quietly crashes on startup.

Any idea about that?

Thx

**Comment by Cheban1996** [comment]
I have the same problem.

**Comment by LukeMathWalker** [comment]
Can you provide a link to a minimum reproducible example?

**Comment by Cheban1996** [comment]
@LukeMathWalker Hi
I created test project https://github.com/Cheban1996/testChef
If i run localy cargo run, app printing message in console
But, if run app from container, it not showing

**Comment by gitmalong** [comment]
> @LukeMathWalker Hi I created test project https://github.com/Cheban1996/testChef If i run locally cargo run, app printing message in console But, if run app from container, it not printing

Shouldn't you copy your source code to the same dir as your Cargo.toml / Cargo.lock? https://github.com/Cheban1996/testChef/blob/main/Dockerfile#L12
```
COPY server/ .
```
instead of
```
COPY Cargo.lock Cargo.toml ./
COPY server/ ./server
```
?

----------

My initial problem is gone. I started from scratch with a new Docker file and then it worked. Should note that I used sccache but problem also occoured without using it.

**Comment by Cheban1996** [comment]
> Shouldn't you copy your source code to the same dir as your Cargo.toml / Cargo.lock? 
In the root directory lie files workspace

I also tried these variants by separately
> COPY server/ .

and

> COPY . .

Nothing from these not working

**Comment by LukeMathWalker** [comment]
You are copying your source files at the wrong stage: they must be brought in _after_ `cook` but _before_ the normal `cargo build` (before this line https://github.com/Cheban1996/testChef/blob/b986bbba0ef02b1ad67cbdd982ee6cd7d6d91558/Dockerfile#L15).
As it stands, `cargo chef cook` overrides your project and `cargo build` is a no-op.
