### ISSUE TITLE
Image not found in Gitlab CI: Missing docker manifest

### ISSUE THREAD

**Issue by azzamsa** [LukeMathWalker/cargo-chef#187]
Hi.

Newer images fail to run in GitLab CI because of the missing manifest.
The older images are fine.

![image](https://user-images.githubusercontent.com/17734314/217144296-323a8786-6547-47e1-90eb-3fee95176151.png)

Credit
- This issue is spotted by @efenfauzi

Thanks for maintaining cargo-chef :heart:

**Comment by LukeMathWalker** [comment]
There were some issues with Docker publishing - they should be solved now, but I'm not going to backfill images for the past versions of the compiler.
Thanks for reporting it!
