### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/communication)

### ISSUE THREAD

**Issue by LukasDeco** [LukeMathWalker/cargo-chef#188]
I used cargo chef to build my image, but my docker run fails with the message: 
```
/usr/local/bin/communication: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/communication)
```

Here is my Dockerfile: 
```
FROM lukemathwalker/cargo-chef:latest-rust-1 AS chef
WORKDIR communication

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /communication/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY . .
RUN cargo build --release --bin communication

# We do not need the Rust toolchain to run the binary!
FROM debian:buster-slim AS runtime
WORKDIR communication
COPY --from=builder /communication/target/release/communication /usr/local/bin
ENTRYPOINT ["/usr/local/bin/communication"]
```

I'm sorry I'm a bit of a noob to Rust. Wasn't sure if this problem had already been ran into?

Thanks!

Update: For extra context here's my Cargo.toml deps
```
async-trait = "0.1.58"
chrono = "0.4.23"
futures = "0.3.25"
gtmpl = "0.7"
openssl = { version = "0.10", features = ["vendored"] }
mongodb = { version = "2.3.1"}
phonenumber = "0.3.1"
regex = "1.3.9"
serde = "1.0.152"
serde_derive = "1.0.151"
serde_json = "1.0.89"
tokio = "1.22.0"
twilio-openapi = "1.2.2"
warp = "0.3"
tera = "1.17.1"
```

**Comment by LukasDeco** [comment]
I added 
```
RUN apt update
RUN apt install libc6
```
Right after the `FROM debian:buster-slim AS runtime`
But that didn't seem to fix it.

**Comment by LukeMathWalker** [comment]
First time seeing this!
Can you provide a minimal reproducible example for me to try to troubleshoot it?

**Comment by LukasDeco** [comment]
I was able to fix this by switching the debian base image to this:
```
FROM debian:bullseye-slim AS runtime
```

It's a more recent image. On the one from the docs, it has 2.28 libc6 installed manually, so even if you try to install it, you'll still have 2.28. Not sure what is the reason my binary is requiring that though. I posted my deps for potential help. Feel free to close this.

**Comment by LukeMathWalker** [comment]
What version of Rust does the builder image use?

**Comment by LukasDeco** [comment]
Whatever is currently on the `lukemathwalker/cargo-chef:latest-rust-1` image.

**Comment by radix** [comment]
This is happening to me, too, using the example from the README (cargo-chef:latest-rust-1 and debian:buster-slim). The recommendation to switch to bullseye-slim is not fixing the problem. This does seem like an incompatibility between the builder and the runtime base image, though, right?

**Comment by LukeMathWalker** [comment]
You need bookworm as runtime, I've updated the README!

**Comment by radix** [comment]
Nice, thank you @LukeMathWalker! :tada:

**Comment by LukasDeco** [comment]
I am coming back to this issue again :joy: is there a reason this keeps needing to be changed? Seems like a very tedious thing to maintain with no long-term solution for the GLIBC version? I was still on `bullseye-slim`, switching to `bookworm-slim` now.

**Comment by LukeMathWalker** [comment]
New Rust versions bump the requirements, that's the reason.
There's no solution, beyond creating a "cargo-chef-runtime" image that swaps Debian version automatically, but that's likely to create a whole other set of issues.
