### ISSUE TITLE
Issue with mongodb crate

### ISSUE THREAD

**Issue by RamDurgaSai** [LukeMathWalker/cargo-chef#191]
------
 > [builder 2/4] RUN cargo chef cook --release --recipe-path recipe.json:
 3.557     Updating crates.io index
437.9 error: failed to select a version for the requirement `time = "^0.3.9"`
437.9 candidate versions found which didn't match: 0.3.15, 0.3.14, 0.3.13, ...
437.9 location searched: crates.io index
437.9 required by package `bson v2.5.0`
437.9     ... which satisfies dependency `bson = "^2.3.0"` (locked to 2.5.0) of package `mongodb v2.3.1`
437.9     ... which satisfies dependency `mongodb = "^2.3.1"` (locked to 2.3.1) of package `mongo-sink v0.0.1 (/app)`
437.9 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.35/src/recipe.rs:145:27
437.9 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------

Cargo.toml file

[package]
name = "mongo-sink"
version = "0.1.0"
edition = "2021"

[dependencies]

tokio = { version = "1", features = ["full"] }
lapin = "1.0.0-rc1"
mongodb = "2.3.1"
tracing = "0.1.37"
tokio-amqp = "2.0.0"
futures-lite = "1.12.0"
serde_json = "1.0.93"
serde = "1.0.152"
tracing-subscriber = { version = "0.3", default-features = false, features = ["alloc"] }

**Comment by joelawm** [comment]
Double check the version of Rust you are using, That was the issue for me. Let me know if that works!

**Comment by moy2010** [comment]
Indeed, this is caused by a mismatch of the version of Rust being used.
