### ISSUE TITLE
Rust 1.68 docker container?

### ISSUE THREAD

**Issue by Arjentix** [LukeMathWalker/cargo-chef#195]
Hello! Do you plan to publish a docker container for `Rust 1.68`?

I'd like to use it to try new [`sparse protocol`](https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol) with your `cargo-chef`.

**Comment by LukeMathWalker** [comment]
I've merged #193 which might fix the build.

**Comment by LukeMathWalker** [comment]
It worked! It's out!
