### ISSUE TITLE
Add support for `--manifest-path` and `--package` cargo flags

### ISSUE THREAD

**Issue by TriplEight** [LukeMathWalker/cargo-chef#21]
```
# cargo chef cook --release --recipe-path recipe.json -- --workspace

error: Found argument '--workspace' which wasn't expected, or isn't valid in this context

If you tried to supply `--workspace` as a PATTERN use `-- --workspace`

USAGE:
    cargo chef cook [FLAGS] [OPTIONS]

For more information try --help
```

Same with pretty much everything, i.e. `--features`, `--package`, etc.
What to do if I want to pre-cache a specific CI job?

**Comment by LukeMathWalker** [comment]
This has been an intentional design choice - cargo flags change the way pieces of logic in cargo-chef have to be executed (e.g. dummy library clean-up based on the target directory).
Can you give me a list of the flags you need? I'll then have a look to add them 👍

**Comment by TriplEight** [comment]
`--package` is needed for sure, both for `prepare` and `cook`. Because in workspace repos there will be different dependencies versions. This means that in cargo cache they will be rewritten every time, hence recompiled over and over. This can be avoided by `cargo-deny` fighting dupes, but it's not something that is real in some cases. By fixing cargo and letting it save several versions of dependencies. Both are not in `chef` project's scope, so adding `--package` seems a good option. Besides, with it, it will become possible managing caches for the different CI jobs more granularly.

Also, I'm not sure how it works with cargo profiles, can you elaborate a bit?

**Comment by LukeMathWalker** [comment]
What do you need `--package` for specifically? Can you provide an example?

About cargo profiles, are you referring to the `--profile` option in `cargo build`?

**Comment by LukeMathWalker** [comment]
Closing given lack of activity. Happy to re-open if the discussion picks up again.

**Comment by TriplEight** [comment]
Sorry for the delay.
I'm trying to make use of `cargo-chef` within the projects with a large virtual workspace, that does not compile everything with a default command. As an easy example, take [ink](https://github.com/paritytech/ink/blob/master/.gitlab-ci.yml), or [substrate](https://github.com/paritytech/substrate/blob/master/.gitlab-ci.yml) for hardcore.
AFAIU simply running `cargo chef cook --release` there won't compile everything that should be mentioned by `--package` or `--manifest-path`.
> About cargo profiles, are you referring to the `--profile` option in cargo build?

[Yes](https://doc.rust-lang.org/cargo/reference/profiles.html), or maybe it respects the config?

**Comment by LukeMathWalker** [comment]
> Yes, or maybe it respects the config?

It should respect the profiles specified in the manifest, but I don't have any project using it, so I wouldn't put my hand on the fire.

> I'm trying to make use of cargo-chef within the projects with a large virtual workspace, that does not compile everything with a default command. As an easy example, take ink, or substrate for hardcore.
AFAIU simply running cargo chef cook --release there won't compile everything that should be mentioned by --package or --manifest-path.

Understood. So you need to `--manifest-path` basically.

**Comment by TriplEight** [comment]
The trouble is I do not have profiles anywhere yet :(
And `--package` with `--workspace` would be handy too!

**Comment by TriplEight** [comment]
maybe makes sense to reopen the issue?

**Comment by LukeMathWalker** [comment]
Renamed and re-opened.

**Comment by sheldonkwok** [comment]
I noticed that using `cargo build --release --package $PACKAGE` doesn't reuse all of the cooked deps. Running `cargo build --release` does though. I haven't been able to look into why that's the case yet.

**Comment by LukeMathWalker** [comment]
To get full re-use (and avoid wasting cycles) you should be able to use `--package` in the `cook` stage - that's what this issue is about 😁
