### ISSUE TITLE
should this work with git dependencies?

### ISSUE THREAD

**Issue by seeekr** [LukeMathWalker/cargo-chef#213]
I've got a workspace and some member crates with dependencies pointing to git repos instead of crates.io. Should cargo-chef work as advertised in that case?

I've used the template from the readme, added install of some compiler debian packages in the builder step, use +nightly for the application compilation step, and adjusted binary name. It seems like I'm getting full dependency rebuilds every time I run a docker build, probably because it's doing a fresh git checkout every time and then the caching doesn't work for some reason?

**Comment by LukeMathWalker** [comment]
It should!
Can you provide a small project to reproduce the issue?

**Comment by seeekr** [comment]
Thanks for the quick response! I'll make one and get back to you as soon as I get around to it!

**Comment by seeekr** [comment]
Hm, it looks like I may have had a .dockerignore issue or something. It keeps just working now (reusing deps cache), and I cannot bring it to break any more :D

So closing this for now, thanks for building + open-sourcing this tool! Great work!

**Comment by Corfucinas** [comment]
> Hm, it looks like I may have had a .dockerignore issue or something. It keeps just working now (reusing deps cache), and I cannot bring it to break any more :D
> 
> So closing this for now, thanks for building + open-sourcing this tool! Great work!

I just ran into the same problem *facepalm*, after compiling with a few toolchains, I figured out that if you have a Git dependency but with a `rev` field included, *AND* you also have in `.dockerignore` the `Cargo.lock`, that it could fail if there's a breaking change in the Git repo.

@seeekr  you might want to take a look at this combination

1) Git crate with a rev (pick one that breaks with latest release)
2) Cargo.lock on .dockerignore

Chef will clone the broken repo (it seems)
