### ISSUE TITLE
Building with local dependencies is broken In recent updates.

### ISSUE THREAD

**Issue by amlatyrngom** [LukeMathWalker/cargo-chef#215]
I recently updated this tool from version `0.1.52` to `0.1.59`. Before the update, I could have something like this:
```toml
[dependencies]
local = {path="./local_path"}
```

Then, after updating the code in `local_path`, `v0.1.52` of `cargo chef cook` would not trigger a full rebuild; it would just rebuild the local dependency. 

After updating to `0.1.59`, I get an error telling me that `local_path/Cargo.toml` has not been found. Fixing this in the Dockerfile would trigger full rebuilds on each update of `local_path`, which would be a huge pain for my project.

It seems like `0.1.59` is actually attempting to build the full local dependency, instead of waiting until `cargo build` is called. Is that right? Shouldn't it only build a dummy version of it with remote dependencies?

P.S.: My repo is private, so I can't point to a concrete example. For now, switching back to `0.1.52` works for me.

**Comment by LukeMathWalker** [comment]
Is the failing local crate some kind of vendored dependency?

**Comment by riyao-lin-simplisafe** [comment]
This [PR](https://github.com/LukeMathWalker/cargo-chef/pull/204) seems to disable the local deps.

**Comment by LukeMathWalker** [comment]
I know that's the change that caused the issue, what I'm trying to understand is why you're experiencing it.
Is this crate part of the workspace you are using `cargo-chef` for? 

A minimal reproducible case is needed to triage.

**Comment by riyao-lin-simplisafe** [comment]
Thanks for looking into it so quickly. The crate is not part of the workspace. Here is rough structure of my app:
```
myapp/
......src/main.rs
......Cargo.toml
......Cargo.lock
......external_crates/external_crate_A/
.......................................src/main.rs
.......................................Cargo.toml
```
Here is the root Cargo.toml
```
[package]
name = "myapp"

[dependencies]
...
external_crate_A = { path = "./external_crates/external_crate_A" }
...
```

**Comment by LukeMathWalker** [comment]
OK, then you need to copy it in before executing `cargo chef cook`.

**Comment by riyao-lin-simplisafe** [comment]
The extra `COPY` does fix the issue. Thanks!
But why didn't we need to do the extra copy in version `0.1.52`?

**Comment by LukeMathWalker** [comment]
The old version of `cargo-chef` was using file traversals to identify which crates should be considered and "emptied out".
This is somewhat error prone, we have therefore switched to a different default: all the crates in the current workspace are considered "local" and will therefore be emptied out, all the other local dependencies are just dependencies and must be copied in (and will be part of the cache, which wasn't the case before).

I'll close this as resolved, let me know if you bump into other issues.
