### ISSUE TITLE
Outdated Alpine tutorial

### ISSUE THREAD

**Issue by azzamsa** [LukeMathWalker/cargo-chef#220]
Hi.

This section of readme https://github.com/LukeMathWalker/cargo-chef#running-the-binary-in-alpine is outdated.
Now cargo-chef has alpine support.

```Dockerfile
FROM lukemathwalker/cargo-chef:latest-rust-1.70.0-alpine3.18 as chef
WORKDIR app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release

FROM scratch
COPY --from=builder /app/target/release/hello /
CMD ["./hello"]
```

Should I make a PR?

**Comment by LukeMathWalker** [comment]
If I remember correctly, the issue is that you often need to have a variety of C libraries available in your build container if you want to build for the musl target, which is were `mustrust` does a better job than our own "vanilla" base image.

**Comment by azzamsa** [comment]
Ooh, I see.
Unfortunately, my simple Axum REST API project works fine with `lukemathwalker/cargo-chef:latest-rust-1.70.0-alpine3.18`.

Thanks.
