### ISSUE TITLE
[Question] How to use Cargo Chef - Docker images and Github Actions

### ISSUE THREAD

**Issue by ajosecueto** [LukeMathWalker/cargo-chef#229]
I'm using github actions to build my docker images and deploy it to my servers, but the docker is build in every action, how to cache in github actions. Someone could provide me an example.

Thanks

**Comment by MPThLee** [comment]
You should use docker cache. With [`actions/cache`](https://github.com/actions/cache), You can do a command line with: https://docs.docker.com/build/cache/backends/
Also with Docker Buildx Github Action for cleaner management: https://docs.docker.com/build/ci/github-actions/cache/ (Note: Some of options still requires `actions/cache`)

**Comment by LukeMathWalker** [comment]
@MPThLee pointed you in the right direction—I'll close this now, but feel free to re-open if you have other doubts.
