### ISSUE TITLE
Benefits over 'manual' caching in readme

### ISSUE THREAD

**Issue by arlyon** [LukeMathWalker/cargo-chef#23]
Hey! Cool tool.

It may be useful for prospective users to have a quick comparison in the readme against using a plain Dockerfile such as this one which seems to be another common solution to the lack of `cargo --build-deps`:

```Dockerfile
FROM clux/muslrust:latest as build-deps
WORKDIR /src

COPY ./Cargo.toml ./Cargo.lock ./
RUN mkdir -p src/ && echo "fn main() { }" > src/main.rs
RUN cargo build --release

FROM build-deps as build-release
COPY ./src ./src
RUN cargo build --release

FROM scratch as release
COPY --from=build-release /src/target/x86_64-unknown-linux-musl/release/server /server
CMD ["/server"]
```

While I understand the benefits, some pros and cons such as buildkit (and maybe a build time comparison) may be nice!

**Comment by LukeMathWalker** [comment]
That's a good point - I discussed the difference between the "current" situation and what `cargo-chef` provides in https://www.lpalmieri.com/posts/fast-rust-docker-builds/ - do you think a link would be enough?

**Comment by arlyon** [comment]
Yeah! It was that article that lead me to this repo. The maintainability aspect is a no-brainer and putting it alongside the limitations would be helpful for new users. I can open a PR to update the readme if you'd like

**Comment by LukeMathWalker** [comment]
Go ahead :grinning:
