### ISSUE TITLE
libssl error with the most recent image

### ISSUE THREAD

**Issue by thomasmost** [LukeMathWalker/cargo-chef#235]
After updating to the 1.72.0 `latest` image, my container will not start due to:

`error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory`

Downgrading to 1.71.1 fixes the issue

**Comment by LukeMathWalker** [comment]
You need to explicitly install your system dependencies. 
This is likely due to a change in what is bundled by our Linux base image, but we don't make any guarantees there.

**Comment by azzamsa** [comment]
@thomasmost would you like to share your solution? I am on the same shoes #246

**Comment by griffinmartin** [comment]
@azzamsa did you end up getting this working without reverting to 1.71.1?

**Comment by azzamsa** [comment]
> @azzamsa did you end up getting this working without reverting to 1.71.1?

Yes. This is my solution https://github.com/LukeMathWalker/cargo-chef/issues/246#issuecomment-1737022449

I get rid all the dependencies that depends on openssl-sys.
