### ISSUE TITLE
Unintended Full Recompilation When Integrating Cargo Chef into Graph Node Dockerfile

### ISSUE THREAD

**Issue by paymog** [LukeMathWalker/cargo-chef#267]
I'm trying to add cargo chef to [this open source project](https://github.com/graphprotocol/graph-node/blob/master/docker/Dockerfile). I've modified the Dockerfile [like so](https://github.com/goldsky-io/graph-node/pull/3/files). When I try to build this, I see a full recompilation happening during the [main build command](https://github.com/goldsky-io/graph-node/pull/3/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcR43). I also see a warning emitted during the cooking phase

```
Step 18/53 : RUN RUSTFLAGS="-g" cargo chef cook --release --recipe-path recipe.json
 ---> Running in 7b1bb385cb88
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
```

Here's the [recipe.json](https://github.com/LukeMathWalker/cargo-chef/files/14885612/recipe.json) file that gets generated.

The docker build command I use is

```
docker build --target graph-node \
            --build-arg "COMMIT_SHA=$(git rev-parse --short HEAD)" \
            --build-arg "REPO_NAME=$(git remote get-url origin | cut -d ":" -f 2 | cut -d "." -f 1)" \
            --build-arg "BRANCH_NAME=$(git branch --show-current)" \
            --build-arg "TAG_NAME=$(git describe --tags --abbrev=0)" \
            -t graph-node:$(git branch --show-current) \
            -f docker/Dockerfile --progress=plain .
```

I checked one of the `*.d` files under `target/release/deps` and I see the hardcoded paths starting with `/graph-node` which seems correct to me.

**Comment by LukeMathWalker** [comment]
On the surface, it looks correct. 
Do you have build logs to share?

**Comment by LukeMathWalker** [comment]
(The resolver warning has nothing to do with `cargo-chef`, that's a `cargo` warning that you need to handle)

**Comment by paymog** [comment]
Yup, here are some build logs: https://gist.github.com/paymog/b71cc9d87add2f8087f97f70ad257f4c

FWIW I don't see that resolver warning when building without `cargo-chef`

**Comment by LukeMathWalker** [comment]
> Yup, here are some build logs: https://gist.github.com/paymog/b71cc9d87add2f8087f97f70ad257f4c
> 
> FWIW I don't see that resolver warning when building without `cargo-chef`

These are the build logs from a fresh run (i.e. [this line](https://gist.github.com/paymog/b71cc9d87add2f8087f97f70ad257f4c#file-gistfile1-txt-L68) would come from the cache otherwise). I need the build logs for a second run that has a warm cache to understand if things are working or not.

**Comment by paymog** [comment]
Whoops, sorry about this. [These logs](https://gist.github.com/paymog/c3f7c5545b8fcb73ae20bd95c2187e1a) should have that stage cached.

**Comment by LukeMathWalker** [comment]
From the logs I can infer that you have a `rust-toolchain.toml` file and that it points to an older version of Rust than the one bundled in `cargo-chef`'s Docker image.
The best course of action, in that case, is to "sync" the Rust version ahead of time—see [this](https://github.com/LukeMathWalker/pavex/blob/580dc5a5870d611d784195d55f548fb280844c82/examples/starter/Dockerfile#L8) as an example.

**Comment by paymog** [comment]
Hmm, I'm not using the `cargo-chef` docker image - I'm using the `chef` [planner image](https://github.com/goldsky-io/graph-node/pull/3/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcR16-R24) as shown [here](https://github.com/LukeMathWalker/cargo-chef?tab=readme-ov-file#without-the-pre-built-image)

**Comment by LukeMathWalker** [comment]
It's the same, you're getting the latest Rust toolchain but your toolchain file wants 1.68.

**Comment by paymog** [comment]
That seems to have fixed it, thank you for your help!
