### ISSUE TITLE
Chef seems to "empty" crates entrypoints

### ISSUE THREAD

**Issue by MatteoJoliveau** [LukeMathWalker/cargo-chef#27]
Hi!
I tried running `cargo chef cook` on [Enseada](https://github.com/enseadaio/enseada), which is composed of several crates linked up into a `server` crate that contains the `main` module.

After running `cook`, all the `lib.rs` become completely empty, and the `main.rs` only contains the following:

```rust
fn main() {}
```

I really don't think this is the desired behaviour 😄 

I was able to reproduce it with a fresh repo: https://github.com/MatteoJoliveau/cargo-chef-repro
The same apply to a repo without dependencies (e.g. a bare repo generated with `cargo new <name>`)

It also modifies the `Cargo.toml` which I really would like to keep the way I wrote it 😅

**Comment by MatteoJoliveau** [comment]
Running cargo-chef 0.1.9 btw

**Comment by MatteoJoliveau** [comment]
By looking a the code I found the function `build_minimum_project` that is invoked by `chef cook` and that requires to be run on a blank canvas. 
Does this mean we should not be using chef locally, or on an existent codebase?
I guess it's fine for building container images but it would have been useful to speedup local development too

**Comment by LukeMathWalker** [comment]
Hey!
`cargo-chef` is indeed designed to be used in containers. I don't see the usecase for local development - what would it give you compared to something like incremental cargo compilation?

**Comment by MatteoJoliveau** [comment]
I guess you're right, I often run `cargo clean` as a habit from other languages where previous compilation results may interfere with the current one, but I guess it's not really necessary given how well cargo works.

Maybe we should document this behaviour nonetheless? Either point out that chef is not really meant to be run outside container builds and/or that it should be run on a clean directory structure.

**Comment by simon-bourne** [comment]
I ran into this as well, when initially trying out `cargo-chef`. While it's not a problem once you figure out how it works, it's a bit surprising while experimenting.

Would it be better to create empty files if they don't exist, or check they are empty if they do exist? This way you can run `cook` on a fresh directory, or re-run it on the same directory (for example to cache debug and release variants), but you'd never overwrite any code.

**Comment by LukeMathWalker** [comment]
I think that's a very good idea @simon-bourne - `cargo chef cook` should exit with a meaningful user warning if it needs to overwrite existing files.

**Comment by MatteoJoliveau** [comment]
@LukeMathWalker couldn't it just skip creating the files if they are already present? I mean, if the goal was to initialize a valid folder structure, having those files already in place means it's already fine.

**Comment by LukeMathWalker** [comment]
The goal is to build a cache for dependencies in the fastest way possible, therefore you want all local projects to be empty otherwise they would significantly increase time to completion for `cargo chef cook`.

**Comment by MatteoJoliveau** [comment]
@LukeMathWalker if you want I can take over this issue and add the following:

- if the TTY is a terminal (detected using [atty](https://docs.rs/atty), print a warning and maybe ask the user for confirmation before proceeding
- update the README with a warning notice about this behaviour

**Comment by LukeMathWalker** [comment]
Go ahead :grin: @MatteoJoliveau

**Comment by adwhit** [comment]
I got bitten by this while trying to run `cargo chef` locally in order to work out why the caching wasn't working.

I wonder if a cleaner solution would be for `cargo-chef` to construct a completely clean repo inside a temporary directory, build as normal, then copy the `target` folder back to the code dir. It seems like this would be safer.

As a bonus, this would allow you to run `cargo-chef` inside sub-directories of workspaces (currently this fails because the target dir is not in the expected location)

**Comment by LukeMathWalker** [comment]
That would indeed be the best of both worlds, but I think there is some work required to strip the absolute path from the dependency files under the `target` folder - I need to dig deeper.

**Comment by LukeMathWalker** [comment]
Closing given #32 has been merged.
