### ISSUE TITLE
cargo-chef missing from docker hub

### ISSUE THREAD

**Issue by johnnybenson** [LukeMathWalker/cargo-chef#270]
Hey just a heads up, it looks like cargo-chef vanished. Not sure if this is intentional.

https://hub.docker.com/r/lukemathwalker/cargo-chef

**Comment by byblakeorriver** [comment]
Yes, very gone. We love cargo-chef!

**Comment by mythosmystery** [comment]
Yeah what's going on here? Why was it removed??

**Comment by alexcstark** [comment]
Blocking my deploys - gonna have to find another solution.

**Comment by byblakeorriver** [comment]
It does look like the command line tool is still available, and can be used like this: 
https://github.com/LukeMathWalker/cargo-chef?tab=readme-ov-file#without-the-pre-built-image

**Comment by pythoninthegrass** [comment]
Just [forked the repo](https://github.com/LukeMathWalker/cargo-chef/compare/main...pythoninthegrass:cargo-chef:main) and built the [latest tags](https://hub.docker.com/repository/docker/jollygoodhorsepower/cargo-chef/tags) if you all need a stopgap

**Comment by pythoninthegrass** [comment]
My workflow looks like this:
```bash
docker pull jollygoodhorsepower/cargo-chef
docker image tag jollygoodhorsepower/cargo-chef lukemathwalker/cargo-chef:0.1.65-rust-1
# docker images | grep lukemathwalker/cargo-chef
cd repo-that-requires-cargo-chef
task docker:build
```

**Comment by i1Fury** [comment]
> Just [forked the repo](https://github.com/LukeMathWalker/cargo-chef/compare/main...pythoninthegrass:cargo-chef:main) and built the [latest tags](https://hub.docker.com/repository/docker/jollygoodhorsepower/cargo-chef/tags) if you all need a stopgap

This was a lifesaver <3 I had an update I had to push asap for my client.

As for why it was delisted, I'd imagine they could have run out of the docker hub subscription... I'm not sure if docker delists popular repos in that instance.

**Comment by LukeMathWalker** [comment]
I definitely didn't delete it, wtf.
Let me investigate.

**Comment by LukeMathWalker** [comment]
Unclear what the hell happened, but I logged into Docker Hub, added a category for the image (since it was marked as "incomplete") and... now it seems to be back online?

**Comment by byblakeorriver** [comment]
Can verify, it is working again! Thank you!

**Comment by LukeMathWalker** [comment]
Nice. I'll mark this as closed then, but I'll keep an eye on it. Please comment again if anything looks amiss.
Good night folks!
