### ISSUE TITLE
Inconsistent recipe files with multiple auto-detected binaries

### ISSUE THREAD

**Issue by markhildreth** [LukeMathWalker/cargo-chef#34]
I have noticed that in a scenario where auto binaries (binaries located in `src/bin`, but with no listing in the manifest) are read in using `complete_from_path`, the order in which the binaries are placed into the resulting manifest structure is not consistent. As a result, the `cargo chef prepare` may generate a few different versions of the recipe file with each call, even if nothing has changed, simply because of this inconsistent ordering.

Note that if the binaries are in the manifest file, rather than being auto-generated, things appear to be okay. That is the current workaround that I am using.

I've opened #33, which provides a potential fix and test case, although I'll admit both are a bit rough. Also, it only fixes auto binaries, I'm sure the same problem might exist with other auto-discovered targets that I'm not as familiar with.

**Comment by LukeMathWalker** [comment]
I merged #33 - thanks a lot for it!

The only other occasion where I think this issue might arise is at the intersection of auto-discovered binaries AND libraries - whether all `[[bin]]` sections are consistently added before or after the autodiscovered `[lib]` entry.
