### ISSUE TITLE
Changing project version, without changing dependency tree, modifies recipe.json and invalidates cache.

### ISSUE THREAD

**Issue by quebin31** [LukeMathWalker/cargo-chef#35]
Is this actually the expected behavior?  From my point of view, changing the project version shouldn't affect the overall build of dependencies, but in this case, this information is included in the `recipe.json` file, and even if you don't change the dependency tree this triggers a full rebuild of dependencies since the cache has been invalidated due to the change.

**Comment by LukeMathWalker** [comment]
It definitely should not happen :sweat_smile: 
It should not be too hard to fix, but it might require fiddling around a bit with the manifests.

**Comment by LukeMathWalker** [comment]
Fixed by #53 thanks to @deantvv
