### ISSUE TITLE
Nondeterminism in recipe.json

### ISSUE THREAD

**Issue by adwhit** [LukeMathWalker/cargo-chef#36]
I have a somewhat complex project for which `cargo-chef` appears to generate the `recipe.json` nondeterministically, which is defeating the caching inside docker.

```
$ cargo chef prepare && md5sum recipe.json
e0f07068fa2eb5406d61e98da3b4df3c  recipe.json
$ cargo chef prepare && md5sum recipe.json
acb5c8b3660c3348a7bc804aa0f58c43  recipe.json
$ cargo chef prepare && md5sum recipe.json
e49e1af1de73aa32ff2f44ce25be9f30  recipe.json
```

The reason for this is that `cargo-chef` is implicitly using a hashmap inside the `toml` dependency. I believe the fix is to update the dep to:
```
toml = {version = "0.5.7", features = ["preserve_order"] }
```

**Comment by adwhit** [comment]
Happy to submit a PR

**Comment by LukeMathWalker** [comment]
Sounds good to me - `cargo-manifest` as well would have to be patched to preserve order.

**Comment by LukeMathWalker** [comment]
Merged and released - thanks for your @adwhit!
