### ISSUE TITLE
Provide Docker image with cargo-chef

### ISSUE THREAD

**Issue by strohel** [LukeMathWalker/cargo-chef#41]
Hi, it would be cool if you could provide a Docker image on Docker Hub with `cargo-chef` installed.

Its Dockerfile could be as simple as
```Dockerfile
FROM rust
RUN cargo install cargo-chef 
```
The README is right that the `RUN cargo install cargo-chef` step gets cached, but that only holds if you run it on the same machine every time. A lot of CIs run each job on a different (virtual) machine, with empty local Docker layer cache.

(it is possible to cache using remote images with --cache-from, --target, and manual pushes/pulls, but it's less convenient)

Thanks for a very helpful tool.

**Comment by LukeMathWalker** [comment]
Not the first time people ask for this 😁 
I'd have to do some research on how to automate the bulk of it (in particular, releases every time Rust or cargo-chef cut a release) but I am open to the idea.

**Comment by strohel** [comment]
I've started looking into this. I think it would be well doable with scheduled GitHub Actions, it can run e.g. every night and exit early if rustc and cargo-chef versions in the current image are up-to-date.
