### ISSUE TITLE
Panic in GitHub Actions

### ISSUE THREAD

**Issue by mkpankov** [LukeMathWalker/cargo-chef#45]
```
#33 747.5 thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.12/src/skeleton.rs:244:60
#33 747.5 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#33 ERROR: executor failed running [/bin/sh -c cargo chef cook --release --recipe-path recipe.json]: exit code: 101
```

The project itself is closed source. I think I can share specific relevant bits if you direct me.

**Comment by LukeMathWalker** [comment]
Hi!
To debug I'd say that we need:
- the version of `cargo-chef` you are using;
- your `Cargo.toml` files.

**Comment by tomusdrw** [comment]
We saw the same today here:
https://github.com/paritytech/parity-bridges-common/runs/1732103007?check_suite_focus=true#step:7:1488

cargo-chef version:
`Installed package `cargo-chef v0.1.12` (executable `cargo-chef`)`

**Comment by LukeMathWalker** [comment]
Interesting - it points to this line: https://github.com/LukeMathWalker/cargo-chef/blob/e1a1697c7886e5a18940acc6f91cc0f4025f37d7/src/skeleton.rs#L244
I'll try to do some debugging this evening.

**Comment by LukeMathWalker** [comment]
Actually, I just released a patched version that should solve the issue (0.1.13) - can you confirm @tomusdrw @mkpankov?

**Comment by HCastano** [comment]
@LukeMathWalker Our CI passes with `v0.1.13`, so I think you can close this 🎉

**Comment by LukeMathWalker** [comment]
Awesome - thanks for confirming @HCastano 😁
