### ISSUE TITLE
cargo-chef doesn't work with workspaces.

### ISSUE THREAD

**Issue by dessalines** [LukeMathWalker/cargo-chef#5]
I have several workspaces in my project, but cargo chef doesn't handle them. The error manifests by showing `unresolved imports` during the `cargo build` section.

Here's what my docker logs show:

```
Plans / Prepares fine.
...
cargo build --release
# Strangely downloads more deps here, when it shouldn't
...
# Strangely compiles only my_app, when it should do the workspaces in the correct order.
#23 41.65    Compiling my_app v0.0.1 (/app) 
#23 51.11 error[E0432]: unresolved imports [all my workspaces that it should've compiled before]
```

If you need me to provide a few commands to replicate this, I can do so.

**Comment by LukeMathWalker** [comment]
Can you provide: 
- a minimum example;
- the version of cargo-chef you are using.

**Comment by dessalines** [comment]
This isn't too minimal, but its what I can reproduce quickly:

```
git clone --single-branch --branch cargo-chef-prod-cache https://github.com/LemmyNet/lemmy
docker build . -f docker/prod/Dockerfile
```

The Dockerfile is taken from the readme. Not sure the exact version of `cargo-chef`, as its installed inside docker.

BTW, the standard output dir is `target/build_target/release_or_debug/...`, but it seems like cargo chef maybe is missing the `build_target` dir?

**Comment by LukeMathWalker** [comment]
You need to specify the target triple using the `--target` option here https://github.com/LemmyNet/lemmy/blob/b30ad829b27450e3e6e47db2f9f4fc8aa3030f38/docker/prod/Dockerfile#L17 I'd say. See #1

**Comment by LukeMathWalker** [comment]
Btw I'll play around with it and see what I come up with :male_detective:

**Comment by LukeMathWalker** [comment]
Our artifact clean-up logic needed some tweaks when customising the target triple.
I got it to work on Lemmy - see https://github.com/LemmyNet/lemmy/pull/1243
