### ISSUE TITLE
Dockerfile example does not properly cache

### ISSUE THREAD

**Issue by hommeabeil** [LukeMathWalker/cargo-chef#54]
I have follow the example for my rust project and it was working well. However, it end up build everything when I was changing a single file in my `src` directory. Does the first stage of the Dockerfile should be something like this

```dockerfile
FROM lukemathwalker/cargo-chef as planner
WORKDIR app
COPY Cargo.tml Cargo.lock .
RUN cargo chef prepare  --recipe-path recipe.json
```

Then the layer will get invalidated only when those 2 files will be modified. Is there a reason for not doing this ?

Thanks

**Comment by LukeMathWalker** [comment]
Can you provide an example project to reproduce the issue?
It does not matter what is copied for layer caching purposes as long as the emitted `recipe.json` is unchanged.

**Comment by hommeabeil** [comment]
After playing a little more with it, you are right everything works well. I might have miss something during my first attempt. Thanks.
