### ISSUE TITLE
How to use cargo-chef in a multi-package repository

### ISSUE THREAD

**Issue by ineiti** [LukeMathWalker/cargo-chef#55]
Thanks very much for this project. I'm trying to clean up my `cp dummy.rs` Dockerfiles using cargo-chef. Unfortunately I have a problem with my multi-project workspace. Given a directory with two projects, like:

```
one - Cargo.toml, src/main.rs
two - Cargo.toml, src/lib.rs
```

When I run `cargo chef prepare` it runs correctly, but `cargo chef cook` complains that it doesn't find the `Cargo.toml` file. What is the correct way to use `cargo chef` here? Should it be run in each subdirectory?

**Comment by LukeMathWalker** [comment]
Can you provide a repository to reproduce? The project structure would be enough, it doesn't have to contain the same code.

Is this a single workspace with two projects inside or are we talking about multiple workspaces (see #4)?

**Comment by ineiti** [comment]
Thanks for taking your time. I put my test-environment in a github repo here:

https://github.com/ineiti/rust-docker

There is a working version in the `Dockerfile`, but I'm not sure it's the best way to do it.

Also, in the final project, this should work with `wasm-pack`. But I'll open another issue for that one.

**Comment by LukeMathWalker** [comment]
Ok, as it is now, you fall into the other issue I mentioned.
If you add a top-level Cargo.toml with a `workspace` entry you should be able to build without having any issue.

**Comment by ineiti** [comment]
_Rust noob here_

I'll try that, thanks!

**Comment by LukeMathWalker** [comment]
No worries at all - check out [the relevant chapter in the Rust book](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) for guidance 😁
