### ISSUE TITLE
Prepare doesn't ignore directories / files with incorrect permissions.

### ISSUE THREAD

**Issue by dessalines** [LukeMathWalker/cargo-chef#6]
I have a few docker volumes directories that require different user permissions, within my git repo (these are in the `.gitignore` and `.dockerignore` obviously). But when running `prepare`, it exits because it can't read those directories, when it should just give a warning.

**Comment by LukeMathWalker** [comment]
Can you create a minimum example for me to work on the issue?

**Comment by dessalines** [comment]
```
cargo new chef_perm_fail
cd chef_perm_fail
sudo mkdir sudodir
sudo chmod 700 sudodir
cargo chef prepare --recipe-path recipe.json
```
...

```
Failed to execute command.
Failed to compute recipe

Caused by:
    0: IO error for operation on /home/tyler/git/chef_perm_fail/sudodir: Permission denied (os error 13)
    1: Permission denied (os error 13)
```
