### ISSUE TITLE
pre-compiled binary

### ISSUE THREAD

**Issue by azzamsa** [LukeMathWalker/cargo-chef#63]
Hi.

I would love to see cargo-chef had pre-compiled binary on the release page.
I tend to avoid invoking the `cargo install` command in CI workflow and downloading the pre-compiled binary directly.
Resulting in just ~14 minutes, compared to ~30 minutes.

So instead of `cargo install trunk`, I do:

```bash
      # install trunk
      wget -qO- https://github.com/thedodd/trunk/releases/download/v0.10.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      chmod +x trunk
      cp trunk ~/.cargo/bin/
      trunk --version
```

I prefer this approach than using `lukemathwalker/cargo-chef` as the base image. So I have more fined grain control over the image.

**Comment by LukeMathWalker** [comment]
I have added CI support for building binaries on release.
You can now download them from https://github.com/LukeMathWalker/cargo-chef/releases
