### ISSUE TITLE
Trying to use cargo chef with ekidd/rust-musl-builder

### ISSUE THREAD

**Issue by marlon-sousa** [LukeMathWalker/cargo-chef#66]
Hello,

Thank you for the great work..

I have an issue I am not sure how to debug to find what is the problem.

I have the following docker file:

```
FROM lukemathwalker/cargo-chef as planner
WORKDIR app
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM lukemathwalker/cargo-chef as cacher
WORKDIR app
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json


FROM ekidd/rust-musl-builder:latest AS builder
COPY --chown=rust:rust . .
# Copy over the cached dependencies
COPY --chown=rust:rust --from=cacher /app/target target
COPY --chown=rust:rust --from=cacher /usr/local/cargo /home/rust/.cargo
# RUN cargo build --release --bin back-office

FROM alpine:latest as runtime
WORKDIR app
COPY --from=builder /home/rust/src/target/x86_64-unknown-linux-musl/release/back-office /usr/local/bin
EXPOSE 8585
ENTRYPOINT ["/usr/local/bin/back-office"]
```

Here, back-office is the name of my package in cargo.toml.

This kind of works ... in the sense that, once the first docker build occurs, if cargo.toml isn't changed, the dependencies aren't downloaded again (the updating crate index ... does not happen at all).

However, the dependencies are compiled at every docker build. I tried many things, because from my point of view what is possibly happening is that the cargo on ekidd/rust-musl-builder takes in consideration stuff on cargo_home but does not recognize stuff coming from targedt from the cacher.

Do you have any hint on how I can fix that so that it works just like if I was using the rust image as builder?

Thanks,
Marlon

**Comment by LukeMathWalker** [comment]
Hi @marlon-sousa!
To help you troubleshoot I need to have a minimal reproducible example of the issue - can you upload a repository with code that runs into the problem you mentioned when building the Docker container?

**Comment by LukeMathWalker** [comment]
Without a minimal reproducible example I am afraid I can't move forward here.
Closing for the time being.
