### ISSUE TITLE
`cargo chef cook` doesn't pre-build all needed dependencies

### ISSUE THREAD

**Issue by soenkehahn** [LukeMathWalker/cargo-chef#68]
I'm trying to use `cargo chef cook` to pre-build all needed dependencies of the [`agora`](https://github.com/soenkehahn/agora) project. But IIUC it fails at doing that.

Here's a repo that reproduces the issue: https://github.com/soenkehahn/cargo-chef-bug

In there, you can execute `./run.sh` to see the bug.

[`RUN cargo chef cook --release --recipe-path recipe.json`](https://github.com/soenkehahn/cargo-chef-bug/blob/master/Dockerfile#L11) will build a bunch of dependencies, but then [`RUN cargo build --release`](https://github.com/soenkehahn/cargo-chef-bug/blob/master/Dockerfile#L14) apparently has to builds (or re-build) not all, but some dependencies. Here's the output of `RUN cargo build --release`:

```
 ---> Running in 4863dc7eb80d
   Compiling syn v1.0.70
   Compiling libc v0.2.94
   Compiling num_cpus v1.13.0
   Compiling mio v0.7.11
   Compiling atty v0.2.14
   Compiling socket2 v0.4.0
   Compiling clap v2.33.3
   Compiling proc-macro-error v1.0.4
   Compiling futures-macro v0.3.14
   Compiling tokio-macros v1.1.0
   Compiling tracing-attributes v0.1.15
   Compiling pin-project-internal v1.0.7
   Compiling maud_macros v0.22.2
   Compiling structopt-derive v0.4.14
   Compiling rust-embed-impl v5.9.0
   Compiling snafu-derive v0.6.10
   Compiling futures-util v0.3.14
   Compiling tokio v1.5.0
   Compiling tracing v0.1.25
   Compiling maud v0.22.2
   Compiling pin-project v1.0.7
   Compiling rust-embed v5.9.0
   Compiling structopt v0.3.21
   Compiling snafu v0.6.10
   Compiling futures-executor v0.3.14
   Compiling futures v0.3.14
   Compiling tokio-util v0.6.6
   Compiling tower v0.4.6
   Compiling h2 v0.3.2
   Compiling hyper v0.14.7
   Compiling agora v0.0.1 (/root/agora)
    Finished release [optimized] target(s) in 1m 21s
Removing intermediate container 4863dc7eb80d
```
If I understand correctly, `cargo chef cook` should pre-build all needed dependencies, so that `cargo build` would only have to build `agora` itself. Am I misunderstanding how `cargo-chef` is supposed to work? Or am I doing something else wrong in my repo? Or is there something going on with `agora` that makes `cargo-chef` misbehave?

Sorry that this is not a minimal reproduction of the problem.

**Comment by soenkehahn** [comment]
`cargo-chef` used to work fine for `agora` some time ago. So the described misbehavior started at some point. I did a `git bisect` in the `agora` project to figure out what causes `cargo-chef` to misbehave. And it's [this commit](https://github.com/soenkehahn/agora/commit/a25aa778699001855cfe51e8b0bd97e84d8df578). That commit sets [`resolver = "2"`](https://github.com/soenkehahn/agora/commit/a25aa778699001855cfe51e8b0bd97e84d8df578#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R6), so I suspect that's the culprit.

Here's the documentation about the resolver: https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2

**Comment by LukeMathWalker** [comment]
Interesting - I haven't had a chance to play with the new resolver yet.
Can you minimise your crate to a smaller example that fails to build incrementally?

**Comment by soenkehahn** [comment]
> Can you minimise your crate to a smaller example that fails to build incrementally?

Sorry, I probably won't find the time to do that soon. If I do I'll let you know!

**Comment by LukeMathWalker** [comment]
Given the above, I'll close for now.

**Comment by markdingram** [comment]
I came across this too & had a quick look why - the workspace Cargo.toml produced by 'cargo chef cook' drops the `resolver = "2" line`

It's possible to patch around this by adding a couple of lines in the docker file:
```
RUN cargo chef cook --tests --recipe-path recipe.json
# Cargo Chef doesn't propagate forward the resolver yet..
RUN sed -i '2 i resolver = "2"' Cargo.toml
RUN cargo build --tests
```

**Comment by LukeMathWalker** [comment]
Then it should be a very easy fix - we just need to add `resolver` to the `cargo-manifest` crate.

**Comment by LukeMathWalker** [comment]
Fixed in `0.1.29`.

**Comment by markdingram** [comment]
Doesn't quite work yet - resolver needs to be added to the workspace struct as well as the package - https://github.com/LukeMathWalker/cargo-manifest/blob/1e232a459aac4b3f0409d2f058928a3b4d6f015c/src/lib.rs#L77

**Comment by LukeMathWalker** [comment]
0.1.30 should do the trick.

**Comment by markdingram** [comment]
Confirmed it does the trick! Thanks
