### ISSUE TITLE
How to speedup Updating crates.io index?

### ISSUE THREAD

**Issue by makorne** [LukeMathWalker/cargo-chef#69]
```
STEP 9: RUN cargo chef cook --release --recipe-path recipe.json
    Updating crates.io index
```

This step takes several times longer to complete than all others.
How to speed it up?
May be use local crate.io mirror?

**Comment by LukeMathWalker** [comment]
Not sure to be honest - that it's usually quite fast in my personal experience.
Is it slow regardless of the environment you run it in? E.g. locally vs in CI? How slow are we talking?

**Comment by makorne** [comment]
Locally.
Looks like it is because of some network issues. 
But random 15-20 minutes waiting is no good.
I think some offline mode might be enough.

**Comment by LukeMathWalker** [comment]
Closing, as it does not look like we can do anything here.
