### ISSUE TITLE
`cargo-chef` isn't local registry aware

### ISSUE THREAD

**Issue by prestontw** [LukeMathWalker/cargo-chef#74]
Link to minimal repo: https://github.com/prestontw/cargo-chef-vendored-repo

I've vendored the dependencies of a small Rocket app using `cargo vendor`. I've then updated `.cargo/config.toml` so that `cargo build` uses the local dependencies. Trying to run `cargo chef` errors with checksum changes (since cargo chef has replaced all of the `lib.rs` files in the dependencies with empty files?).

I'm thinking if we make `cargo chef` aware of `.cargo/config.toml`, we will know not to skelefy these vendored files.

Aside: using `cargo-local-registry` is fine since it stores dependencies in zipped files, so `cargo chef` doesn't skelefy them.

**Comment by LukeMathWalker** [comment]
`.cargo/config.toml` is already part of the recipe file, so it should be possible to make this work without any changes to the CLI parameters.
