### ISSUE TITLE
Fail to build due to change in `clap`

### ISSUE THREAD

**Issue by johnmave126** [LukeMathWalker/cargo-chef#77]
Although the dependency of `clap` is specified as `3.0.0-beta.2`, it turns out that when performing `cargo install cargo-chef`, cargo always pulls the newest version matching semvar, ignoring the beta part. So at this moment, cargo will pull `3.0.0-beta.4` version of `clap` to build `cargo-chef`.

Due to change in https://github.com/clap-rs/clap/pull/2686
https://github.com/LukeMathWalker/cargo-chef/blob/b331984848ee760c9099d5a95fd700cbe7358ce1/src/main.rs#L76
fails to compile since `value_delimiter` now accepts `char` instead of `&str`.

I will do a fork and submit a pr for this.

**Comment by BeneSim** [comment]
i did comment the PR but I'd also like to add that as a workaround you could simply use `cargo install cargo-chef --locked` at the moment to use the `Cargo.lock` file which does work. You won't get any potential security updates whatsoever but at least you'd have a working CI/CD pipeline again until the PR from @johnmave126 gets merged.

**Comment by LukeMathWalker** [comment]
My mistake here - I should have pinned `clap`'s version using `=`, preventing `cargo` from pulling in the latest semver-compatible version.
