### ISSUE TITLE
`cargo-chef` sees wrong version number 0.0.1

### ISSUE THREAD

**Issue by joepio** [LukeMathWalker/cargo-chef#84]
Hi there, thanks for this awesome crate, have been using it with success for months. However, since a couple of days my docker [builds](https://github.com/joepio/atomic-data-rust/runs/3381921615?check_suite_focus=true#step:5:347) for [atomic-server](https://github.com/joepio/atomic-data-rust/) are failing:

```
#17 [cacher 5/5] RUN cargo chef cook --release --recipe-path recipe.json
#17 0.858 error: failed to select a version for the requirement `atomic_lib = "^0.25.6"`
#17 0.858 candidate versions found which didn't match: 0.0.1
#17 0.858 location searched: /app/lib
#17 0.858 required by package `atomic-server v0.0.1 (/app/server)`
#17 0.859 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.24/src/recipe.rs:142:27
#17 0.859 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#17 ERROR: executor failed running [/bin/sh -c cargo chef cook --release --recipe-path recipe.json]: exit code: 101
```

If I'm understanding this correctly, cargo sees the candidate version as version 0.0.1, while the `cargo.toml` indicates 0.25.6.

I've tried `cargo install`ing older versions of cargo-chef:

```dockerfile
RUN cargo install cargo-chef --version 0.1.20
```

 but these fail (tried 0.1.20, 0.1.22):

```
#12 88.10 error[E0308]: mismatched types
#12 88.10   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.20/src/main.rs:73:58
#12 88.10    |
#12 88.10 73 |     #[clap(long, use_delimiter = true, value_delimiter = ",")]
#12 88.10    |                                                          ^^^ expected `char`, found `&str`
#12 88.10 
#12 88.13 error: aborting due to previous error
```

Running `cargo build --release --bin atomic-server` works fine on my machine.

Any ideas on what I could try? Thanks again!

**Comment by LukeMathWalker** [comment]
We perform version masking for local crates to avoid losing the dependency cache if the dependency tree has not changed.
I believe this is an issue with our substitution logic - when checking the `Cargo.toml` of your CLI (https://github.com/joepio/atomic-data-rust/blob/master/cli/Cargo.toml) we are looking for `atomic-lib` while the `-` transforms into a `_` when listing it as a dependency. 
Therefore we fail to update the requirement in the `Cargo.toml` of your CLI, leading to the error. 

I can work on a fix.

**Comment by joepio** [comment]
Thanks for the very quick reply and analysis! Fix would be awesome :)

**Comment by LukeMathWalker** [comment]
Can you test again using `0.1.25`? @joepio

**Comment by joepio** [comment]
Seems to be working! Thanks so much for your quick help.

Still shows the incorrect `0.0.1` version in the logs, but the build succeeds.

```
#17 377.5    Compiling atomic-server v0.0.1 (/app/server)
```

**Comment by LukeMathWalker** [comment]
That's by design :) 
Version masking ensures that your cache layer is only invalidated for changes to your external dependency tree 👍

I'll close then, thanks for reporting it!
