### ISSUE TITLE
Only pre-release versions are pushed to Docker Hub?

### ISSUE THREAD

**Issue by ciffelia** [LukeMathWalker/cargo-chef#86]
Hi, thanks for this awesome project!

It seems that all images on docker hub have `-alpha.0` suffix in their version part (e.g. `0.1.26-alpha.0-rust-latest`, `0.1.25-alpha.0-rust-latest`).
https://hub.docker.com/r/lukemathwalker/cargo-chef/tags

I think these are pre-release versions, but I can't find any version tagged without this suffix (e.g. `0.1.26-rust-latest`, `0.1.25-rust-latest`).
Is this expected behavior?

**Comment by LukeMathWalker** [comment]
This is definitely a bug!

**Comment by LukeMathWalker** [comment]
It looks like it started between `0.1.22` and `0.1.23` 🤔

**Comment by jmagnusson** [comment]
@LukeMathWalker I'm pretty sure it's because the Build Docker Images workflow is only triggered once per push, using the latest commit. My guess is that you push the release version and the alpha release version in the same push, no? This would explain why.

I'll make a PR.

**Comment by jmagnusson** [comment]
PR pushed now. @LukeMathWalker once merged, perhaps you could tag 0.1.27 to try it out? It is a patch version after all 😉

**Comment by LukeMathWalker** [comment]
The CI pipeline has been fixed - tags have been released for 1.26, so you can refer to those @ciffelia!

**Comment by ciffelia** [comment]
thanks!
